valuesFilePath: ./values.yaml

resources:
  - name: myGitRepo
    type: GitRepo
    configuration: 
      gitProvider: {{.Values.myRepo.gitProvider}}
      path: {{.Values.myRepo.path}}
      branches:
        include: master

pipelines:
  - name: Shashank's pipeline
    steps: 
      - name: step1
        type: Bash
        configuration: 
          inputResources: 
            - name: myGitRepo
        execution:
          onExecute:
            - echo "onExecute Command Invoked"
          onSuccess:
            - echo "onSuccess Command Invoked"
          onComplete:
            - echo "onComplete Command Invoked"
