resources: 
  - name: npm_repo_jfp_example
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: shashankGithub
      # Repository path, including org name/repo name
      path: shashank-taliwal/hello-world-nodejs
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

  - name: npm_build_source
    type: BuildInfo
    configuration:
      sourceArtifactory: shashankArtifact

pipelines: 
  - name: shashank_npm_start
    steps:
      - name: step1
        type: NpmBuild
        configuration:
          repositoryName: quickstarts-npm-virtual      # required, npm repository name on artifacctory
          sourceLocation: .      # required, location of package.json file
          integrations:
            - name:    shashankArtifact # required
          inputResources:
            - name: npm_repo_jfp_example      # required

      - name: npm_publish_step
        type: NpmPublish
        configuration:
          # for payloadType npm:
          repositoryName: quickstarts-npm-virtual        # required, npm repository name on artifactory
          autoPublishBuildInfo: true       # optional
          integrations:
            - name:  shashankArtifact     # required
          inputSteps:
            - name: step1                # required
          outputResources:
            - name: npm_build_source                 # optional

